// Curated catalogs for non-Phosphor icon libraries. Names match the asset
// filenames of the corresponding npm packages (served via unpkg at runtime).
// All are permissively licensed (MIT / Apache 2.0).

// Lucide (MIT) — kebab-case. Package: lucide-static
// CDN: https://unpkg.com/lucide-static@<ver>/icons/<name>.svg
export const LUCIDE_ICONS: readonly string[] = [
  'activity', 'airplay', 'alarm-clock', 'album', 'alert-circle', 'alert-triangle',
  'archive', 'arrow-down', 'arrow-down-left', 'arrow-down-right', 'arrow-left',
  'arrow-right', 'arrow-up', 'arrow-up-left', 'arrow-up-right', 'at-sign',
  'award', 'backpack', 'baggage-claim', 'banknote', 'bar-chart', 'battery',
  'battery-charging', 'battery-full', 'battery-low', 'bed', 'beer', 'bell',
  'bell-off', 'bike', 'bird', 'bluetooth', 'bold', 'book', 'book-open',
  'bookmark', 'box', 'briefcase', 'bug', 'building', 'bus', 'cable', 'cake',
  'calculator', 'calendar', 'camera', 'camera-off', 'car', 'cast', 'check',
  'check-circle', 'chevron-down', 'chevron-left', 'chevron-right', 'chevron-up',
  'chrome', 'circle', 'clipboard', 'clock', 'cloud', 'cloud-rain', 'cloud-snow',
  'code', 'codepen', 'codesandbox', 'coffee', 'coins', 'command', 'compass',
  'copy', 'copyright', 'credit-card', 'crop', 'crosshair', 'crown', 'database',
  'diamond', 'disc', 'dna', 'dollar-sign', 'download', 'droplet', 'edit',
  'external-link', 'eye', 'eye-off', 'facebook', 'feather', 'figma', 'file',
  'file-text', 'film', 'filter', 'flag', 'flame', 'flashlight', 'flask-conical',
  'folder', 'folder-open', 'gamepad', 'gamepad-2', 'gem', 'gift', 'git-branch',
  'git-commit', 'git-merge', 'git-pull-request', 'github', 'gitlab', 'glasses',
  'globe', 'graduation-cap', 'grid', 'hammer', 'hand', 'hard-drive', 'hash',
  'headphones', 'heart', 'help-circle', 'home', 'hotel', 'image', 'inbox',
  'info', 'italic', 'key', 'keyboard', 'lamp', 'laptop', 'layers', 'layout',
  'leaf', 'library', 'lightbulb', 'link', 'linkedin', 'list', 'loader', 'lock',
  'log-in', 'log-out', 'luggage', 'mail', 'map', 'map-pin', 'maximize', 'medal',
  'megaphone', 'menu', 'message-circle', 'message-square', 'mic', 'mic-off',
  'minus', 'monitor', 'moon', 'more-horizontal', 'more-vertical', 'mouse',
  'move', 'music', 'navigation', 'newspaper', 'octagon', 'package', 'paint-bucket',
  'palette', 'paperclip', 'pause', 'pencil', 'percent', 'phone', 'phone-call',
  'pie-chart', 'pin', 'pizza', 'plane', 'play', 'plug', 'plus', 'pocket',
  'power', 'printer', 'puzzle', 'qr-code', 'quote', 'radio', 'receipt',
  'refresh-ccw', 'refresh-cw', 'repeat', 'reply', 'rocket', 'rotate-ccw',
  'rotate-cw', 'save', 'scale', 'scan', 'scissors', 'search', 'send', 'server',
  'settings', 'share', 'shield', 'ship', 'shirt', 'shopping-bag', 'shopping-cart',
  'shuffle', 'sidebar', 'signal', 'skip-back', 'skip-forward', 'slash', 'smartphone',
  'smile', 'sofa', 'speaker', 'sprout', 'square', 'star', 'sticky-note', 'stop-circle',
  'store', 'sun', 'sunrise', 'sunset', 'table', 'tablet', 'tag', 'target',
  'terminal', 'thermometer', 'thumbs-down', 'thumbs-up', 'ticket', 'timer',
  'train', 'trash', 'tree-pine', 'trending-down', 'trending-up', 'triangle',
  'trophy', 'truck', 'tv', 'twitter', 'type', 'umbrella', 'underline', 'unlock',
  'upload', 'user', 'user-check', 'user-plus', 'user-x', 'users', 'utensils',
  'video', 'voicemail', 'volume', 'wallet', 'watch', 'wifi', 'wind', 'wine',
  'wrench', 'x', 'youtube', 'zap', 'zoom-in', 'zoom-out',
];

// Heroicons (MIT) — kebab-case. Package: heroicons (24/outline)
// CDN: https://unpkg.com/heroicons@<ver>/24/outline/<name>.svg
export const HEROICONS: readonly string[] = [
  'academic-cap', 'adjustments-horizontal', 'archive-box', 'arrow-down', 'arrow-down-tray',
  'arrow-left', 'arrow-path', 'arrow-right', 'arrow-top-right-on-square', 'arrow-up',
  'arrow-up-tray', 'arrow-uturn-left', 'at-symbol', 'backward', 'banknotes',
  'bars-3', 'bars-4', 'battery-100', 'beaker', 'bell', 'bolt', 'book-open',
  'bookmark', 'briefcase', 'bug-ant', 'building-library', 'building-office',
  'building-storefront', 'cake', 'calculator', 'calendar', 'camera', 'chart-bar',
  'chart-pie', 'chat-bubble-left', 'chat-bubble-left-right', 'check', 'check-badge',
  'check-circle', 'chevron-down', 'chevron-left', 'chevron-right', 'chevron-up',
  'circle-stack', 'clipboard', 'clipboard-document', 'clock', 'cloud', 'cloud-arrow-down',
  'cloud-arrow-up', 'code-bracket', 'cog', 'cog-6-tooth', 'command-line',
  'computer-desktop', 'cpu-chip', 'credit-card', 'cube', 'currency-dollar',
  'device-phone-mobile', 'device-tablet', 'document', 'document-text',
  'ellipsis-horizontal', 'ellipsis-vertical', 'envelope', 'envelope-open',
  'exclamation-circle', 'exclamation-triangle', 'eye', 'eye-slash', 'face-frown',
  'face-smile', 'film', 'finger-print', 'fire', 'flag', 'folder', 'folder-open',
  'folder-plus', 'forward', 'funnel', 'gift', 'globe-alt', 'hand-raised',
  'hand-thumb-down', 'hand-thumb-up', 'hashtag', 'heart', 'home', 'home-modern',
  'identification', 'inbox', 'inbox-arrow-down', 'information-circle', 'key',
  'language', 'light-bulb', 'link', 'list-bullet', 'lock-closed', 'lock-open',
  'magnifying-glass', 'map', 'map-pin', 'megaphone', 'microphone', 'minus',
  'minus-circle', 'moon', 'musical-note', 'newspaper', 'paint-brush', 'paper-airplane',
  'paper-clip', 'pencil', 'pencil-square', 'phone', 'phone-arrow-down-left',
  'photo', 'play', 'play-circle', 'plus', 'plus-circle', 'power', 'printer',
  'puzzle-piece', 'qr-code', 'question-mark-circle', 'queue-list', 'radio',
  'receipt-percent', 'receipt-refund', 'rectangle-group', 'rectangle-stack',
  'rocket-launch', 'rss', 'scale', 'scissors', 'server', 'share', 'shield-check',
  'shield-exclamation', 'shopping-bag', 'shopping-cart', 'signal', 'sparkles',
  'speaker-wave', 'speaker-x-mark', 'square-2-stack', 'squares-2x2', 'squares-plus',
  'star', 'stop', 'sun', 'swatch', 'table-cells', 'tag', 'ticket', 'trash',
  'trophy', 'truck', 'tv', 'user', 'user-circle', 'user-group', 'user-plus',
  'users', 'variable', 'video-camera', 'view-columns', 'viewfinder-circle',
  'wallet', 'wifi', 'window', 'wrench', 'wrench-screwdriver', 'x-circle',
  'x-mark',
];

// Material Symbols (Apache 2.0) — snake_case. Package: @material-design-icons/svg
// CDN: https://unpkg.com/@material-design-icons/svg@<ver>/outlined/<name>.svg
export const MATERIAL_ICONS: readonly string[] = [
  'add', 'add_circle', 'alarm', 'analytics', 'apartment', 'apps', 'architecture',
  'arrow_back', 'arrow_downward', 'arrow_drop_down', 'arrow_forward', 'arrow_upward',
  'article', 'assessment', 'assignment', 'atm', 'attach_file', 'attach_money',
  'attachment', 'auto_awesome', 'backup', 'badge', 'bakery_dining', 'bar_chart',
  'bathtub', 'battery_full', 'beach_access', 'bed', 'bedtime', 'block', 'bluetooth',
  'bolt', 'book', 'bookmark', 'brush', 'bug_report', 'build', 'business',
  'cached', 'cake', 'calculate', 'calendar_today', 'call', 'camera', 'camera_alt',
  'campaign', 'cancel', 'card_giftcard', 'casino', 'celebration', 'chair', 'chat',
  'check', 'check_box', 'check_circle', 'chevron_left', 'chevron_right', 'close',
  'cloud', 'cloud_download', 'cloud_upload', 'code', 'coffee', 'collections',
  'comment', 'computer', 'confirmation_number', 'construction', 'contacts',
  'content_copy', 'content_cut', 'content_paste', 'create', 'credit_card', 'dashboard',
  'delete', 'description', 'desktop_windows', 'diamond', 'directions_car',
  'directions_run', 'directions_walk', 'dns', 'done', 'done_all', 'download',
  'drafts', 'drag_handle', 'edit', 'email', 'emoji_events', 'emoji_people',
  'error', 'event', 'explore', 'extension', 'favorite', 'feedback', 'filter_list',
  'flag', 'flight', 'folder', 'folder_open', 'forum', 'forward', 'fullscreen',
  'gps_fixed', 'grade', 'grid_view', 'group', 'hail', 'handshake', 'hardware',
  'headphones', 'help', 'highlight', 'history', 'home', 'hotel', 'hourglass_empty',
  'house', 'how_to_reg', 'info', 'insert_chart', 'inventory', 'key', 'keyboard',
  'label', 'language', 'laptop', 'layers', 'light_mode', 'lightbulb', 'link',
  'list', 'local_bar', 'local_cafe', 'local_fire_department', 'local_grocery_store',
  'local_hospital', 'local_mall', 'local_offer', 'local_parking', 'local_pharmacy',
  'local_pizza', 'local_shipping', 'location_on', 'lock', 'login', 'logout',
  'loyalty', 'mail', 'map', 'menu', 'mic', 'mic_off', 'mms', 'mood', 'more_horiz',
  'more_vert', 'motorcycle', 'mouse', 'movie', 'music_note', 'navigation',
  'nights_stay', 'notifications', 'pageview', 'palette', 'park', 'pause',
  'payments', 'people', 'person', 'person_add', 'pets', 'phone', 'photo',
  'photo_camera', 'pie_chart', 'place', 'play_arrow', 'policy', 'power', 'print',
  'privacy_tip', 'public', 'push_pin', 'qr_code', 'query_stats', 'question_answer',
  'quiz', 'radio', 'radar', 'receipt', 'recycling', 'redeem', 'refresh', 'remove',
  'reply', 'report', 'restaurant', 'restore', 'rocket_launch', 'room', 'rowing',
  'rss_feed', 'save', 'savings', 'school', 'science', 'search', 'security',
  'send', 'sentiment_satisfied', 'settings', 'share', 'shield', 'shopping_bag',
  'shopping_cart', 'shower', 'smartphone', 'smoking_rooms', 'snowboarding',
  'spa', 'speed', 'sports_basketball', 'sports_soccer', 'star', 'store',
  'storefront', 'subscriptions', 'summarize', 'support_agent', 'surfing',
  'swap_horiz', 'sync', 'tab', 'table_chart', 'tablet', 'task', 'terminal',
  'thumb_down', 'thumb_up', 'timer', 'today', 'toll', 'touch_app', 'tour',
  'track_changes', 'traffic', 'train', 'translate', 'trending_up', 'trip_origin',
  'tune', 'tv', 'umbrella', 'upload', 'verified', 'videocam', 'view_list',
  'visibility', 'visibility_off', 'volume_up', 'wallet', 'warning', 'watch',
  'water_drop', 'wb_sunny', 'wc', 'whatshot', 'widgets', 'wifi', 'work',
  'workspace_premium', 'yard', 'zoom_in', 'zoom_out',
];
